# Generated by Django 6.0.2 on 2026-04-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_healthdata_healthprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthprofile',
            old_name='bp_dia',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='healthprofile',
            old_name='bp_sys',
            new_name='bp',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='age',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='gender',
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='sugar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.signup'),
        ),
        migrations.DeleteModel(
            name='HealthData',
        ),
    ]
