# Generated by Django 6.0.2 on 2026-04-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_rename_bp_dia_healthprofile_age_and_more'),
    ]

    operations = [
    ]
