# Generated by Django 6.0.2 on 2026-04-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_dailyentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.signup'),
        ),
    ]
